### ISSUE TITLE
idea about webhook

### ISSUE THREAD

**Issue by AkiaCode** [harmony-org/harmony#31]
It's made by myself, but is this right?

![image](https://user-images.githubusercontent.com/71239005/98485952-84c8ff00-225d-11eb-97a0-348e9f026567.png)

And how about putting webhooks in ClientOption too?
![image](https://user-images.githubusercontent.com/71239005/98485997-ebe6b380-225d-11eb-9fde-21358714391e.png)

Docs: https://discord.com/developers/docs/resources/webhook

**Comment by Helloyunho** [comment]
> It's made by myself, but is this right?

I think it's okay but you should at least throw an error when the name is not valid.

> And how about putting webhooks in ClientOption too?

What do you mean?

**Comment by AkiaCode** [comment]
> > It's made by myself, but is this right?
> 
> I think it's okay but you should at least throw an error when the name is not valid.
> 
okay, But if I throw an error in return, I can't solve it because there's an error.
> > And how about putting webhooks in ClientOption too?
> 
> What do you mean?

client.<Webhook>

**Comment by AkiaCode** [comment]
ex) client.webhook(id, token).create('name')

**Comment by 6days9weeks** [comment]
why use client.<Webhook>? webhooks are server related not bot related

**Comment by AkiaCode** [comment]
> why use client.? webhooks are server related not bot related


It seemed necessary because there was a client in the first code

**Comment by 6days9weeks** [comment]
> > why use client.? webhooks are server related not bot related
> 
> It seemed necessary because there was a client in the first code

If I'm not wrong the first code meant the client makes a webhook for themselves in the server where it was used.(correct me if am wrong)

**Comment by AkiaCode** [comment]
So, can I just not use the client? @6days9weeks

**Comment by 6days9weeks** [comment]
You can use client I'm not saying you can't but what would be the possible use for it in ClientOption, auto-webhook for the bot?

**Comment by AkiaCode** [comment]
idk

**Comment by 6days9weeks** [comment]
lmao, then if you want to then add it

**Comment by AkiaCode** [comment]
okay
