### ISSUE TITLE
TypeError: Cannot read property 'remaining' of undefined

### ISSUE THREAD

**Issue by mogoh** [harmony-org/harmony#33]
I get this error when trying the ping-example:

```
$ deno run --allow-net ping.ts 
harmony - ping example
Input Bot Token: <token removed by hand>
Input Intents (0 = All, 1 = Presence, 2 = Server Members, 3 = None): 0
error: Uncaught (in promise) TypeError: Cannot read property 'remaining' of undefined
      if (info.session_start_limit.remaining === 0)
                                   ^
    at Gateway.sendIdentify (index.ts:198:36)
    at async Gateway.onmessage (index.ts:88:11)
```

I am not sure, if I do something wrong but it looks like the error is not on my side.

**Comment by DjDeveloperr** [comment]
I just tested it (reloaded the cache too), and it's working fine

![image](https://user-images.githubusercontent.com/43033058/98935375-730b8400-2509-11eb-9442-7ead048a5abb.png)

What Deno version are you using?

**Comment by 6days9weeks** [comment]
Tested with the latest Deno version available on a Ubuntu VM works for me.

**Comment by mogoh** [comment]
I think I accidentally used the wrong token. :thinking: I will check that.

```
deno --version
deno 1.5.2 (71d7482, release, x86_64-unknown-linux-gnu)
v8 8.7.220.3
typescript 4.0.5
```

```
$ deno run --allow-net https://raw.githubusercontent.com/harmony-org/harmony/main/examples/ping.ts
harmony - ping example
Input Bot Token: <toke removed by hand>
Input Intents (0 = All, 1 = Presence, 2 = Server Members, 3 = None): 1
error: Uncaught (in promise) TypeError: Cannot read property 'remaining' of undefined
      if (info.session_start_limit.remaining === 0)
                                   ^
    at Gateway.sendIdentify (index.ts:198:36)
    at async Gateway.onmessage (index.ts:88:11)
```

**Comment by DjDeveloperr** [comment]
Confirmed, it's because of wrong token.

![image](https://user-images.githubusercontent.com/43033058/98936873-9c2d1400-250b-11eb-8f40-979ead58082a.png)

**Comment by mogoh** [comment]
Thank you.
I just got it working.
The error is misleading, but I think you probably agree on that.
