### ISSUE TITLE
 License Inquiries

### ISSUE THREAD

**Issue by SaidBySolo** [harmony-org/harmony#34]
Currently, Harmony's license is an MIT license and copyright holder is Helloyunho.

But harmony-org owns the repository.

Therefore, how about putting the copyright holder under the harmony-org?

**Comment by adolphin-hitler** [comment]
For now, the org doesn’t fully own the repository and Helloyunho is the only maintainer.

**Comment by SaidBySolo** [comment]
@AkiaCode 
This issue is related to licensing. It is not related to the pullique.

**Comment by adolphin-hitler** [comment]
@SaidBySolo You kinda sus. Bringing my army to hunt you down.

**Comment by DjDeveloperr** [comment]
Harmony Org is now the License holder - this should be clear now.
