### ISSUE TITLE
Export Interfaces for docs

### ISSUE THREAD

**Issue by CyberKnight007** [harmony-org/harmony#49]
Many class's constructors have Interfaces as parameters but since the Interface is not exported from mod.ts so they don't appear in the docs.. 
If someone, who is new to the library, will check the docs then he will go hella confused because we have many of these un-exported interfaces
Like this one class:
![image](https://user-images.githubusercontent.com/67542663/101057311-ec027680-35b1-11eb-8885-b089b47dea73.png)

**Comment by DjDeveloperr** [comment]
Those classes aren't meant to be directly constructed by user.

**Comment by ayntee** [comment]
You cannot construct/instantiate an interface. :sweat_smile:

**Comment by DjDeveloperr** [comment]
> 
> 
> You cannot construct/instantiate an interface. 😅

I mean classes like `GuildIntegration`, `Message` ... those are constructed and returned by Managers only.

**Comment by Preta-Crowz** [comment]
I think they can be used to other advanced things too

**Comment by DjDeveloperr** [comment]
True, I don't mind exporting them 👍 and `raw` event can be used to access the raw payloads of events dispatched.

**Comment by CyberKnight007** [comment]
If this is done then i think we can close this issue?

**Comment by DjDeveloperr** [comment]
Closing as fixed.
