### ISSUE TITLE
Bot tries reconnect infinite times after session resets

### ISSUE THREAD

**Issue by Preta-Crowz** [harmony-org/harmony#50]
Debug Log : https://pastebin.com/ucJSYsbN (Only after limit<10), https://pastebin.com/3LshT4Ds (Full log from console)
When bot starts once, then session will resets after 24 hours.
And when session resets, bot will start to cause error and keep reconnect to reach session limit.
I can't find what's first error from console because its log was too long and exceeds console limit.
Only remain codes are two : 1000, 4005

**Comment by DjDeveloperr** [comment]
I'll check this ASAP, to me it looks like a problem with `seq` or other props not being reset at reconnect.

**Comment by Helloyunho** [comment]
![image](https://user-images.githubusercontent.com/10192625/101115300-797fae00-3626-11eb-972e-7b91a1ef96fc.png)
Hmm

**Comment by Preta-Crowz** [comment]
yes. 4005 is already authenticated and 1000 is unknown error.

**Comment by Helloyunho** [comment]
![image](https://user-images.githubusercontent.com/10192625/101115612-fad74080-3626-11eb-91c4-18f4a1cd5b4e.png)
1000 is normal closure(means closed without any errors)

**Comment by DjDeveloperr** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/10192625/101115612-fad74080-3626-11eb-91c4-18f4a1cd5b4e.png)
> 1000 is normal closure(means closed without any errors)

How are we supposed to handle that?

**Comment by Helloyunho** [comment]
> > ![image](https://user-images.githubusercontent.com/10192625/101115612-fad74080-3626-11eb-91c4-18f4a1cd5b4e.png)
> > 1000 is normal closure(means closed without any errors)
> 
> How are we supposed to handle that?

Just reconnect with cached session I guess?

**Comment by DjDeveloperr** [comment]
So, what you said is already being done i.e. reconnects with cached session. Looks like socket immediately closes after INVALID_SESSION is dispatched, what do you think about doing nothing when we receive INVALID_SESSION?

**Comment by AkiaCode** [comment]
> 그래서, 당신이 말한 것은 이미 수행되고 있습니다. 즉, 캐시 된 세션과 다시 연결됩니다. INVALID_SESSION이 발송 된 후 소켓이 즉시 닫히는 것 같습니다. INVALID_SESSION을 받으면 아무것도하지 않는 것에 대해 어떻게 생각하십니까?

I think it would be better to show the error

**Comment by Helloyunho** [comment]
> So, what you said is already being done i.e. reconnects with cached session. Looks like socket immediately closes after INVALID_SESSION is dispatched, what do you think about doing nothing when we receive INVALID_SESSION?

Actually it doesn't even reconnect. It just resends the identify data.
![image](https://user-images.githubusercontent.com/10192625/101117357-29a2e600-362a-11eb-93f6-d32d528dc3ef.png)

**Comment by DjDeveloperr** [comment]
That's what I mean, we shouldn't be re-identifying there **with timeout**. Socket closes after we receive that, and we end up with two identifies.

**Comment by Helloyunho** [comment]
That's the reason why it gives 4005, right?

**Comment by DjDeveloperr** [comment]
> 
> 
> That's the reason why it gives 4005, right?

Exactly. Should I remove that?

**Comment by Helloyunho** [comment]
> > That's the reason why it gives 4005, right?
> 
> Exactly. Should I remove that?

Yeah.

**Comment by Preta-Crowz** [comment]
I'll make file hander to save logs today and result will be got on tomorrow

**Comment by DjDeveloperr** [comment]
> 
> 
> I'll make file hander to save logs today and result will be got on tomorrow

Can you try using latest code from `main` branch after I push the changes?

**Comment by CyberKnight007** [comment]
The same thing happened to me yesterday but it solved when i switched my network so i didn't find the need to report it :/

**Comment by Preta-Crowz** [comment]
> 
> 
> > I'll make file hander to save logs today and result will be got on tomorrow
> 
> Can you try using latest code from `main` branch after I push the changes?

Sure. I'll do it

**Comment by Preta-Crowz** [comment]
fixed!
