### ISSUE TITLE
No webhook create, message edit, message delete method?

### ISSUE THREAD

**Issue by AkiaCode** [harmony-org/harmony#57]
https://github.com/harmony-org/harmony/blob/e403a62a0b628d071bb6612f0f47e1b10d080edd/src/structures/webhook.ts

**Comment by DjDeveloperr** [comment]
Webhook create is supposed to be in GuildTextChannel. And yeah Message edit and delete are missing.

**Comment by AkiaCode** [comment]
> Webhook create is supposed to be in GuildTextChannel. And yeah Message edit and delete are missing.

So you can't make it?

**Comment by DjDeveloperr** [comment]
I'll add them to my current PR I think.

**Comment by AkiaCode** [comment]
> I'll add them to my current PR I think.

Okay, thank you

**Comment by DjDeveloperr** [comment]
Closing as this has been added since my PR was merged.
